FROM node:20-alpine

WORKDIR /app

COPY infra/prisma/package.json ./package.json
COPY infra/prisma/tsconfig.json ./tsconfig.json
RUN npm install

COPY infra/prisma/schema.prisma ./prisma/schema.prisma
COPY infra/prisma/seed.ts ./prisma/seed.ts
RUN npx prisma generate

CMD ["npx", "prisma", "db", "seed"]
