FROM node:20-alpine

WORKDIR /app

COPY infra/prisma/package.json ./package.json
RUN npm install

COPY infra/prisma/schema.prisma ./prisma/schema.prisma
COPY infra/prisma/migrations/ ./prisma/migrations/

CMD ["npx", "prisma", "migrate", "deploy"]
