// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/login": {
            "post": {
                "description": "Authenticate an admin user and receive a bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Admin login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/events/hit": {
            "post": {
                "description": "Process a hit event sent from a physical laser tag device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Register a hit",
                "parameters": [
                    {
                        "description": "Hit event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.HitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all games.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "List games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.GameResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new laser tag game with the given configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Create a game",
                "parameters": [
                    {
                        "description": "Game definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a game by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Get a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.GameResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/control": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Execute an admin action (revive, kick, change_team, restart, etc.).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Admin control",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Control command",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ControlCommandRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/end": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "End a running or paused game and persist final state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "End a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/join": {
            "post": {
                "description": "Register a player (with device and gun) into an existing game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Join a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Player data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.JoinRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.GamePlayerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/leaderboard": {
            "get": {
                "description": "Retrieve sorted leaderboard entries for a game.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "Get leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.LeaderboardEntryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pause a currently running game.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Pause a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/players": {
            "get": {
                "description": "Get all players currently registered in a game.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Players"
                ],
                "summary": "List players",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.GamePlayerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transition a game from pending to running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Start a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/state": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the live state of a game from cache (players, scores, timer).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.GameLiveStateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/games/{id}/teams": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a new team to an existing game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Create a team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ControlCommandRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "revive_player"
                },
                "game_id": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                },
                "player_id": {
                    "type": "string",
                    "example": "player-uuid"
                }
            }
        },
        "http.CreateGameRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/http.GameConfig"
                },
                "name": {
                    "type": "string",
                    "example": "Friday Night Match"
                }
            }
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "something went wrong"
                }
            }
        },
        "http.FeedbackConfig": {
            "type": "object",
            "properties": {
                "intensity": {
                    "type": "integer",
                    "example": 80
                },
                "led_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "sound_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "vibration_enabled": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "http.GameConfig": {
            "type": "object",
            "properties": {
                "duration_seconds": {
                    "type": "integer",
                    "example": 300
                },
                "feedback": {
                    "$ref": "#/definitions/http.FeedbackConfig"
                },
                "game_mode": {
                    "type": "string",
                    "example": "team_deathmatch"
                },
                "max_players": {
                    "type": "integer",
                    "example": 20
                },
                "player": {
                    "$ref": "#/definitions/http.PlayerConfig"
                },
                "scoring": {
                    "$ref": "#/definitions/http.ScoringConfig"
                },
                "team_count": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "http.GameLiveStateResponse": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "running"
                },
                "team_scores": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "time_remaining_s": {
                    "type": "integer",
                    "example": 180
                }
            }
        },
        "http.GamePlayerResponse": {
            "type": "object",
            "properties": {
                "deaths": {
                    "type": "integer",
                    "example": 0
                },
                "device_id": {
                    "type": "string",
                    "example": "vest-01"
                },
                "game_id": {
                    "type": "string"
                },
                "gun_id": {
                    "type": "string",
                    "example": "gun-01"
                },
                "hp": {
                    "type": "integer",
                    "example": 100
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_alive": {
                    "type": "boolean",
                    "example": true
                },
                "kills": {
                    "type": "integer",
                    "example": 0
                },
                "lives_remaining": {
                    "type": "integer",
                    "example": 3
                },
                "nickname": {
                    "type": "string",
                    "example": "Player1"
                },
                "score": {
                    "type": "integer",
                    "example": 0
                },
                "team_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "weapon_id": {
                    "type": "string"
                }
            }
        },
        "http.GameResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/http.GameConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Friday Night Match"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "http.HitEventDetail": {
            "type": "object",
            "properties": {
                "damage": {
                    "type": "integer",
                    "example": 25
                },
                "device_id": {
                    "type": "string",
                    "example": "vest-01"
                },
                "is_headshot": {
                    "type": "boolean",
                    "example": false
                },
                "target_id": {
                    "type": "string",
                    "example": "vest-02"
                },
                "weapon_id": {
                    "type": "string",
                    "example": "wpn-1"
                }
            }
        },
        "http.HitRequest": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "hit": {
                    "$ref": "#/definitions/http.HitEventDetail"
                }
            }
        },
        "http.JoinRequest": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "vest-01"
                },
                "gun_id": {
                    "type": "string",
                    "example": "gun-01"
                },
                "nickname": {
                    "type": "string",
                    "example": "Player1"
                },
                "team_id": {
                    "type": "string",
                    "example": "team-uuid"
                },
                "user_id": {
                    "type": "string",
                    "example": "user-uuid"
                },
                "weapon_id": {
                    "type": "string",
                    "example": "wpn-1"
                }
            }
        },
        "http.LeaderboardEntryResponse": {
            "type": "object",
            "properties": {
                "damage_dealt": {
                    "type": "integer",
                    "example": 1250
                },
                "deaths": {
                    "type": "integer",
                    "example": 2
                },
                "kills": {
                    "type": "integer",
                    "example": 5
                },
                "nickname": {
                    "type": "string",
                    "example": "Player1"
                },
                "player_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer",
                    "example": 350
                },
                "team_id": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string",
                    "example": "Red Team"
                }
            }
        },
        "http.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secret"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "http.PlayerConfig": {
            "type": "object",
            "properties": {
                "friendly_fire": {
                    "type": "boolean",
                    "example": false
                },
                "lives": {
                    "type": "integer",
                    "example": 3
                },
                "max_hp": {
                    "type": "integer",
                    "example": 100
                },
                "respawn_delay_seconds": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "http.ScoringConfig": {
            "type": "object",
            "properties": {
                "headshot_multiplier": {
                    "type": "number",
                    "example": 2
                },
                "points_per_hit": {
                    "type": "integer",
                    "example": 10
                },
                "points_per_kill": {
                    "type": "integer",
                    "example": 100
                },
                "teamkill_penalty": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "http.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.TeamRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#FF0000"
                },
                "name": {
                    "type": "string",
                    "example": "Red Team"
                }
            }
        },
        "http.TeamResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#FF0000"
                },
                "game_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Red Team"
                }
            }
        },
        "http.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "abc123..."
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter \"Bearer {token}\" (without quotes)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Laser Tag Game API",
	Description:      "Real-time configurable laser tag game engine backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
